config/routes.rb
Rails3app::Application.routes.draw do
  get "home/index"

  get "user_sessions/new"
  resources :user_sessions
  resources :users
  resources :articles do
    resources :comments
  end
  resources :comments
  match 'register' => "users#new", :as => :register
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => 'articles#index'
  resources :password_resets

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new # guest user
    
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :create, Comment
      can :update, Comment do |comment|
        comment.try(:user) == user
      end
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  has_many :articles
  has_many :comments
  
  def self.find_by_login_or_email(login)
    User.find_by_login(login) || User.find_by_email(login)
  end
  
  def deliver_password_reset_instructions!
     reset_perishable_token!
     Notifier.deliver_password_reset_instructions(self)
  end
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  find_by_login_method :find_by_login_or_email
  
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user_session, :current_user

  private
    def current_user_session
      logger.debug "ApplicationController::current_user_session"
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      logger.debug "ApplicationController::current_user"
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end

    def require_user
      logger.debug "ApplicationController::require_user"
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      logger.debug "ApplicationController::require_no_user"
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to root_url
#        redirect_to account_url
        return false
      end
    end

    def store_location
      session[:return_to] = request.request_uri
    end

    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  
  def index
    @articles = Article.find(:all)
  end
  
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new(:article => @article)
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params[:article])
    @article.user = current_user
    if @article.save
      flash[:notice] = "Successfully created article."
      redirect_to @article
    else
      render :action => 'new'
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = "Successfully updated article."
      redirect_to @article
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Successfully destroyed article."
    redirect_to articles_url
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  
  def new
  end
  
  def create
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "Successfully created comment."
      redirect_to article_url(@comment.article_id)
    else
      render :action => 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @comment.update_attributes(params[:comment])
      flash[:notice] = "Successfully updated comment."
      redirect_to article_url(@comment.article_id)
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @comment.destroy
    flash[:notice] = "Successfully destroyed comment."
    redirect_to article_url(@comment.article_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

 before_filter :load_user_using_perishable_token, :only => [:edit, :update]
 before_filter :require_no_user

 def new
   render
 end

 def create
   @user = User.find_by_email(params[:email])
   if @user
     @user.deliver_password_reset_instructions!
     flash[:notice] = "Instructions to reset your password have been emailed to you. " +
     "Please check your email."
     redirect_to root_url
   else
     flash[:notice] = "No user was found with that email address"
     render :action => :new
   end
 end

 def edit
  render
 end

 def update
   @user.password = params[:user][:password]
   @user.password_confirmation = params[:user][:password_confirmation]
   if @user.save
     flash[:notice] = "Password successfully updated"
     redirect_to account_url
   else
    render :action => :edit
   end
 end

private
 def load_user_using_perishable_token
   @user = User.find_using_perishable_token(params[:id])
   unless @user
   flash[:notice] = "We're sorry, but we could not locate your account. " +
   "If you are having issues try copying and pasting the URL " +
   "from your email into your browser or restarting the " +
   "reset password process."
   redirect_to root_url
   end
 end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
        # uses a block to prevent double render error...
        # because oauth and openid use redirects
        @user_session.save do |result|
          if result
            flash[:notice] = "Login successful!"
            if current_user
              redirect_back_or_default root_url
            else
              redirect_to new_user_session_url
            end
          else
            render :action => :new
          end
        end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Registration successful."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated profile."
      redirect_to root_url
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args.map(&:to_s)) }
  end

  def javascript(*args)
    args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= error_messages_for :article %>
<% form_for @article do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :author_name %><br />
    <%= f.text_field :author_name %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/articles/edit.html.erb
<% title "Edit Article" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @article %> |
  <%= link_to "View All", articles_path %>
</p>

app/views/articles/index.html.erb
<% title "Articles" %>

<div id="articles">
<% for article in @articles %>
  <h2>
    <%= link_to h(article.name), article %>
    <span class="comments">(<%= pluralize(article.comments.size, 'comment') %>)</span>
  </h2>
  <div class="author">from <%=h article.author_name %> on <%= article.created_at.strftime('%b %d, %Y') %></div>
  <div class="content"><%= simple_format(article.content) %></div>
<% end %>
</div>

<% if can? :create, Article %>
  <p><%= link_to "New Article", new_article_path %></p>
<% end %>

app/views/articles/new.html.erb
<% title "New Article" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", articles_path %></p>

app/views/articles/show.html.erb
<% title @article.name %>

<p class="author"><em>from <%=h @article.author_name %></em></p>

<%= simple_format @article.content %>

<p>
  <% if can? :update, @article %>
    <%= link_to "Edit", edit_article_path(@article) %> |
  <% end %>
  <% if can? :destroy, @article %>
    <%= link_to "Destroy", @article, :method => :delete, :confirm => "Are you sure?" %> |
  <% end %>
  <%= link_to "Back to Articles", articles_path %>
</p>

<% unless @article.comments.empty? %>
  <h2><%= pluralize(@article.comments.size, 'comment') %></h2>

  <div id="comments">
  <% for comment in @article.comments %>
    <div class="comment">
      <strong><%= link_to_unless comment.site_url.blank?, h(comment.author_name), h(comment.site_url) %></strong>
      <em>on <%= comment.created_at.strftime('%b %d, %Y at %H:%M') %></em>
      <%=simple_format comment.content %>
      <p>
        <% if can? :update, comment %>
          <%= link_to "Edit", edit_comment_path(comment) %>
        <% end %>
        <% if can? :destroy, comment %>
          | <%= link_to "Destroy", comment, :method => :delete, :confirm => "Are you sure?" %>
        <% end %>
      </p>
    </div>
  <% end %>
  </div>
<% end %>

<h3>Add your comment:</h3>
<%= render :partial => 'comments/form' %>

app/views/comments/_form.html.erb
<%= error_messages_for :comment %>
<% form_for @comment do |f| %>
  <%= f.hidden_field :article_id %>
  <p>
    <%= f.label :author_name, 'Name' %><br />
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :site_url, 'Website URL' %><br />
    <%= f.text_field :site_url %>
  </p>
  <p>
    <%= f.label :content, 'Comment' %><br />
    <%= f.text_area :content, :rows => '12', :cols => 35 %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/comments/edit.html.erb
<% title "Edit Comment" %>

<%= render :partial => 'form' %>

app/views/comments/new.html.erb
<% title "New Comment" %>

<%= render :partial => 'form' %>

app/views/home/index.html.erb
fsdjkfjsdkafjsdkafjkdsjf

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3app</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
    <div id="container">
      <div id="user_nav">
        <% if current_user %>
          <%= link_to "Edit Profile", edit_user_path(:current) %> |
          <%= link_to "Logout", logout_path %>
        <% else %>
          <%= link_to "Register", register_path %> |
          <%= link_to "Login", login_path %>
        <% end %>
      </div>

      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>

      <%- if show_title? -%>
        <h1><%=h yield(:title) %></h1>
      <%- end -%>

      <%= yield %>
    </div>

</body>
</html>

app/views/notifier/password_reset_instructions.erb
A request to reset your password has been made.
If you did not make this request, simply ignore this email.
If you did make this request just click the link below:
   <%=@edit_password_reset_url %>
If the above URL does not work try copying and pasting it into your browser.
If you continue to have problem please feel free to contact us.

app/views/password_resets/edit.html.erb
<h1>Change My Password</h1>

<% form_for @user, :url => password_reset_path, :method => :put do |f| %>
  <%= f.error_messages %>
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %><br />
  <br />
  <%= f.submit "Update my password and log me in" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Password</h1>

Fill out the form below and instructions to reset your password will be emailed to you:<br />
<br />

<% form_tag password_resets_path do %>
  <label>Email:</label><br />
  <%= text_field_tag "email" %><br />
  <br />
  <%= submit_tag "Reset my password" %>
<% end %>

app/views/user_sessions/new.html.erb
<%= form_for @user_session, :url => {:action => "create"} do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :remember_me %><br />
    <%= f.check_box :remember_me %>
  </p>
  <%=oauth_login_hidden_input%>
  <p><%= f.submit "Submit" %></p>
<% end %>



<%= button_to "Sign in with Twitter", { :controller => 'user_sessions', :action => 'create', :oauth_provider => 'twitter', :authentication_type => 'session' }, :class => 'sign-in-twitter-button'%>

app/views/users/_form.html.erb
<% form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :login %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Edit User" %>

<%= render :partial => 'form' %>

app/views/users/new.html.erb
<% title "New User" %>

<%= render :partial => 'form' %>